repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--config-data, '{extends: default, rules: {line-length: disable}}']

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.0
    hooks:
      - id: sqlfluff-lint
        name: SQLFluff Lint
        args: [--dialect, postgres]
      - id: sqlfluff-fix
        name: SQLFluff Fix
        args: [--dialect, postgres]
        stages: [commit]

  - repo: local
    hooks:
      - id: dbt-parse
        name: dbt parse
        entry: dbt parse
        language: system
        files: ^(models|macros|tests|dbt_project\.yml|packages\.yml)
        pass_filenames: false
