services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jaffle
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: olist_dbt
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: jaffle
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./target:/app/target
      - ./logs:/app/logs
    profiles:
      - dbt

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist_dashboard
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: jaffle
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dashboard.py:/app/dashboard.py
    restart: unless-stopped

volumes:
  pg_data:
